[pytest]
addopts = -rsfEw --basetemp=/tmp/pytest-my-registrations
python_files = *_test.py
indico_plugins = my_registrations
filterwarnings =
    error
    ignore::sqlalchemy.exc.SAWarning
    ignore::UserWarning
redis_exec = redis-server
